name: Run Puppeteer to enable or disable Boost

on:
  schedule:
    - cron: "30 5 * * *"  # 11:30 PM GMT-6 (5:30 AM UTC)
    - cron: "0 22 * * *"   # 4:00 PM GMT-6 (10:00 PM UTC)
  workflow_dispatch:
    inputs:
      boost_mode:
        description: "Indica si deseas establecer el Boost en True o en False"
        required: true
        default: "false"  # Valor por defecto si no se especifica

jobs:
  run-puppeteer:
    name: Run Puppeteer to change Boost/Train Normal
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install Dependencies
        run: npm install

      - name: Determine Boost Mode
        id: set_mode
        run: |
          # Usar la marca de tiempo del evento para establecer el tiempo de inicio
          START_TIME=$(echo "${{ github.event.timestamp }}" | awk '{print $1 " " $2}' | cut -d. -f1)
          CURRENT_TIME=$(date -d "$START_TIME" '+%H:%M')

          echo "Job started at UTC time: $CURRENT_TIME"

          # Comparar horas
          if [[ "$CURRENT_TIME" == "05:30" ]]; then  # 11:30 PM GMT-6
            echo "Boost mode is set to true"
            echo "boost_mode=true" >> $GITHUB_ENV
          elif [[ "$CURRENT_TIME" == "22:00" ]]; then  # 4:00 PM GMT-6
            echo "Boost mode is set to false"
            echo "boost_mode=false" >> $GITHUB_ENV
          else
            echo "Warning: The start time does not match any expected times."
            echo "boost_mode=${{ github.event.inputs.boost_mode }}" >> $GITHUB_ENV  # Usar valor manual
          fi

      - name: Run Puppeteer Script
        env:
          USER_PASSWORD: ${{ secrets.USER_PASSWORD }}
          IS_TRAIN_BOOST: ${{ env.boost_mode }}  # Usar la variable del entorno
        run: node boostTrainingChange.js

      - name: Upload error screenshot
        if: failure() # Only upload if the job fails
        uses: actions/upload-artifact@v4
        with:
          name: error-screenshots
          path: error-screenshot-*.png