name: Run Puppeteer to enable or disable Boost

on:
  schedule:
    - cron: "30 5 * * *"  # 11:30 PM GMT-6 (5:30 AM UTC)
    - cron: "0 22 * * *"  # 4:00 PM GMT-6 (10:00 PM UTC)
  workflow_dispatch:  # Permite ejecución manual

jobs:
  run-puppeteer-night:
    name: Run Puppeteer at 11:30 PM - Enable Boost
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install Dependencies
        run: npm install

      - name: Run Puppeteer Script (Night)
        env:
          PUPPETEER_PASSWORD: ${{ secrets.PUPPETEER_PASSWORD }}
          IS_TRAIN_BOOST: "true"  # Se ejecuta de noche
        run: node script.js

  run-puppeteer-afternoon:
    name: Run Puppeteer at 4:00 PM - Disable Boost/Train Normal
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install Dependencies
        run: npm install

      - name: Run Puppeteer Script (Afternoon)
        env:
          PUPPETEER_PASSWORD: ${{ secrets.PUPPETEER_PASSWORD }}
          IS_TRAIN_BOOST: "false"  # Se ejecuta en la tarde
        run: node script.js
